name: moodio
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  phosphor_flutter: ^2.1.0
  lottie: ^3.3.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_svg: ^2.2.0
  flutter_carousel_slider: ^1.1.0
  animated_emoji: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/

  